/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'ch.indiemusi.alpha.actor.publishingOwner'

export { $nsid }

/** A songwriter, composer, or music publisher who owns the publishing rights to a song or musical work */
type Main = {
  $type: 'ch.indiemusi.alpha.actor.publishingOwner'
  firstName?: string
  lastName?: string
  companyName?: string

  /**
   * Interested Party Information (IPI) number assigned to the publishing owner by a collecting society
   */
  ipi?: string
  collectingSociety?: string
}

export type { Main }

/** A songwriter, composer, or music publisher who owns the publishing rights to a song or musical work */
const main = l.record<'tid', Main>(
  'tid',
  $nsid,
  l.object({
    firstName: l.optional(l.string({ maxLength: 255 })),
    lastName: l.optional(l.string({ maxLength: 255 })),
    companyName: l.optional(l.string({ maxLength: 255 })),
    ipi: l.optional(l.string({ maxLength: 11 })),
    collectingSociety: l.optional(l.string({ maxLength: 255 })),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
