/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'ch.indiemusi.alpha.audioFile'

export { $nsid }

/** An audio file stored inside a user's private atproto space of type ch.indiemusi.alpha.audioLibrary. Not stored in the public repo. */
type Main = {
  $type: 'ch.indiemusi.alpha.audioFile'

  /**
   * The raw audio blob, stored inside the space.
   */
  audio: l.BlobRef

  /**
   * MIME type of the audio blob, e.g. audio/flac.
   */
  mimeType: string

  /**
   * Duration of the audio in seconds.
   */
  duration?: number

  /**
   * Size of the audio file in bytes.
   */
  byteSize?: number

  /**
   * Audio encoding details, e.g. 'FLAC 24-bit / 96kHz stereo'.
   */
  encoding?: string
  createdAt?: l.DatetimeString
}

export type { Main }

/** An audio file stored inside a user's private atproto space of type ch.indiemusi.alpha.audioLibrary. Not stored in the public repo. */
const main = l.record<'tid', Main>(
  'tid',
  $nsid,
  l.object({
    audio: l.blob({
      accept: [
        'audio/flac',
        'audio/mpeg',
        'audio/wav',
        'audio/aac',
        'audio/ogg',
      ],
      allowLegacy: false,
    }),
    mimeType: l.string({ maxLength: 127 }),
    duration: l.optional(l.integer()),
    byteSize: l.optional(l.integer()),
    encoding: l.optional(l.string({ maxLength: 255 })),
    createdAt: l.optional(l.string({ format: 'datetime' })),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
