/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as AlphaSong from './song.defs'
import * as ActorArtist from './actor/artist.defs'
import * as ActorMasterOwner from './actor/masterOwner.defs'

const $nsid = 'ch.indiemusi.alpha.recording'

export { $nsid }

/** A recording of a song or musical work: the performance captured in a specific format */
type Main = {
  $type: 'ch.indiemusi.alpha.recording'
  title: string
  song?: AlphaSong.Main
  artists: Artist[]

  /**
   * ISRC (International Standard Recording Code) with which the recording is registered
   */
  isrc?: string
  masterOwner?: MasterOwnerInfo

  /**
   * Duration of the recording in seconds
   */
  duration?: number

  /**
   * Reference to the access-controlled audio file stored in the owner's atproto space.
   */
  audioFile?: AudioFileRef
}

export type { Main }

/** A recording of a song or musical work: the performance captured in a specific format */
const main = l.record<'tid', Main>(
  'tid',
  $nsid,
  l.object({
    title: l.string({ maxLength: 255 }),
    song: l.optional(l.ref<AlphaSong.Main>((() => AlphaSong.main) as any)),
    artists: l.array(l.ref<Artist>((() => artist) as any), { minLength: 1 }),
    isrc: l.optional(l.string({ maxLength: 12 })),
    masterOwner: l.optional(
      l.ref<MasterOwnerInfo>((() => masterOwnerInfo) as any),
    ),
    duration: l.optional(l.integer()),
    audioFile: l.optional(l.ref<AudioFileRef>((() => audioFileRef) as any)),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)

/** Pointer to a ch.indiemusi.alpha.audioFile record in the owner's private space. Requires a space credential from the owner's PDS to retrieve the audio blob. */
type AudioFileRef = {
  $type?: 'ch.indiemusi.alpha.recording#audioFileRef'

  /**
   * DID of the user whose space hosts the audio file record.
   */
  ownerDid: l.DidString

  /**
   * Space key of the ch.indiemusi.alpha.audioLibrary space holding this file. Corresponds to the rkey of the associated release record.
   */
  spaceSkey: string

  /**
   * Record key of the ch.indiemusi.alpha.audioFile record within the space.
   */
  rkey: string

  /**
   * MIME type hint, e.g. audio/flac. Allows display without fetching the space record.
   */
  mimeType?: string
}

export type { AudioFileRef }

/** Pointer to a ch.indiemusi.alpha.audioFile record in the owner's private space. Requires a space credential from the owner's PDS to retrieve the audio blob. */
const audioFileRef = l.typedObject<AudioFileRef>(
  $nsid,
  'audioFileRef',
  l.object({
    ownerDid: l.string({ format: 'did' }),
    spaceSkey: l.string({ maxLength: 512 }),
    rkey: l.string({ maxLength: 512 }),
    mimeType: l.optional(l.string({ maxLength: 127 })),
  }),
)

export { audioFileRef }

/** Information about an artist contributing to the recording */
type Artist = {
  $type?: 'ch.indiemusi.alpha.recording#artist'
  name: string
  did?: l.DidString
  artist?: ActorArtist.Main
}

export type { Artist }

/** Information about an artist contributing to the recording */
const artist = l.typedObject<Artist>(
  $nsid,
  'artist',
  l.object({
    name: l.string({ maxLength: 255 }),
    did: l.optional(l.string({ format: 'did' })),
    artist: l.optional(
      l.ref<ActorArtist.Main>((() => ActorArtist.main) as any),
    ),
  }),
)

export { artist }

/** Information about the master owner */
type MasterOwnerInfo = {
  $type?: 'ch.indiemusi.alpha.recording#masterOwnerInfo'
  name?: string
  did?: l.DidString
  masterOwner?: ActorMasterOwner.Main
}

export type { MasterOwnerInfo }

/** Information about the master owner */
const masterOwnerInfo = l.typedObject<MasterOwnerInfo>(
  $nsid,
  'masterOwnerInfo',
  l.object({
    name: l.optional(l.string({ maxLength: 255 })),
    did: l.optional(l.string({ format: 'did' })),
    masterOwner: l.optional(
      l.ref<ActorMasterOwner.Main>((() => ActorMasterOwner.main) as any),
    ),
  }),
)

export { masterOwnerInfo }
