/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as AlphaRecording from './recording.defs'
import * as ActorArtist from './actor/artist.defs'

const $nsid = 'ch.indiemusi.alpha.release'

export { $nsid }

/** A release (album, EP, single) containing recordings of songs or musical works */
type Main = {
  $type: 'ch.indiemusi.alpha.release'
  title: string
  artists: Artist[]

  /**
   * GTIN (Global Trade Item Number) with which the release is registered, e.g. EAN or UPC
   */
  gtin?: string
  releaseDate?: l.DatetimeString
  artworkImage?: l.BlobRef

  /**
   * List of recordings (ch.indiemusi.alpha.recording) included in this release
   */
  recordings: AlphaRecording.Main[]
}

export type { Main }

/** A release (album, EP, single) containing recordings of songs or musical works */
const main = l.record<'tid', Main>(
  'tid',
  $nsid,
  l.object({
    title: l.string({ maxLength: 255 }),
    artists: l.array(l.ref<Artist>((() => artist) as any), { minLength: 1 }),
    gtin: l.optional(l.string({ maxLength: 14 })),
    releaseDate: l.optional(l.string({ format: 'datetime' })),
    artworkImage: l.optional(l.blob({ allowLegacy: false })),
    recordings: l.array(
      l.ref<AlphaRecording.Main>((() => AlphaRecording.main) as any),
      { minLength: 1 },
    ),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)

/** Information about an artist contributing to the release */
type Artist = {
  $type?: 'ch.indiemusi.alpha.release#artist'
  name: string
  did?: l.DidString
  artist?: ActorArtist.Main
}

export type { Artist }

/** Information about an artist contributing to the release */
const artist = l.typedObject<Artist>(
  $nsid,
  'artist',
  l.object({
    name: l.string({ maxLength: 255 }),
    did: l.optional(l.string({ format: 'did' })),
    artist: l.optional(
      l.ref<ActorArtist.Main>((() => ActorArtist.main) as any),
    ),
  }),
)

export { artist }
