/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as ActorPublishingOwner from './actor/publishingOwner.defs'

const $nsid = 'ch.indiemusi.alpha.song'

export { $nsid }

/** A song or musical work: the melody, lyrics, and arrangement created by composers and authors */
type Main = {
  $type: 'ch.indiemusi.alpha.song'
  title: string

  /**
   * ISWC (International Standard Musical Work Code) with which the song is registered at a collecting society
   */
  iswc?: string

  /**
   * List of interested parties (authors, composers, publishers) associated with this song
   */
  interestedParties: InterestedParty[]
}

export type { Main }

/** A song or musical work: the melody, lyrics, and arrangement created by composers and authors */
const main = l.record<'tid', Main>(
  'tid',
  $nsid,
  l.object({
    title: l.string({ maxLength: 255 }),
    iswc: l.optional(l.string({ maxLength: 13 })),
    interestedParties: l.array(
      l.ref<InterestedParty>((() => interestedParty) as any),
      { minLength: 1 },
    ),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)

/** An interested party associated with the song (author, composer, publisher) */
type InterestedParty = {
  $type?: 'ch.indiemusi.alpha.song#interestedParty'
  name?: string

  /**
   * Role of the interested party (e.g., 'author', 'composer', 'publisher')
   */
  role?: string
  ipi?: string
  collectingSociety?: string

  /**
   * Percentage of performance royalties allocated to this interested party, 10000 = 100%
   */
  performanceRoyaltiesPercentage?: number

  /**
   * Percentage of mechanical royalties allocated to this interested party, 10000 = 100%
   */
  mechanicalRoyaltiesPercentage?: number
  did?: l.DidString
  publishingOwner?: ActorPublishingOwner.Main
}

export type { InterestedParty }

/** An interested party associated with the song (author, composer, publisher) */
const interestedParty = l.typedObject<InterestedParty>(
  $nsid,
  'interestedParty',
  l.object({
    name: l.optional(l.string({ maxLength: 255 })),
    role: l.optional(l.string({ maxLength: 255 })),
    ipi: l.optional(l.string({ maxLength: 11 })),
    collectingSociety: l.optional(l.string({ maxLength: 255 })),
    performanceRoyaltiesPercentage: l.optional(l.integer()),
    mechanicalRoyaltiesPercentage: l.optional(l.integer()),
    did: l.optional(l.string({ format: 'did' })),
    publishingOwner: l.optional(
      l.ref<ActorPublishingOwner.Main>(
        (() => ActorPublishingOwner.main) as any,
      ),
    ),
  }),
)

export { interestedParty }
